---
- name: update nodes
  hosts: all
  become: true
  tasks:
    - name: update debian
      ansible.builtin.apt:
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"

    - name: update redhat
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

- name: deploy web service node
  hosts: [srv_web_prod, srv_web_dev]
  become: true
  roles:
    - web_role


- name: deploy db service node
  hosts: [srv_db_prod, srv_db_dev]
  become: true
  roles:
    - db_role